### ISSUE TITLE
Error loading github: cannot import name formatting (../../sopel_modules/github/github.py:21)

### ISSUE THREAD

**Issue by dredhorse** [sopel-irc/sopel-github#1]
Trying to run this on OSX 10.10.5, I did install via pip install sopel_modules.github.

Any idea?

**Comment by maxpowa** [comment]
Python version?

**Comment by dredhorse** [comment]
Python 2.7.9 (default, Feb 10 2015, 03:28:08)

**Comment by Techbot121** [comment]
I know this is like over three months old, but I've had the same issue. 
I fixed it by replacing some of the imports as follows:

from github.py
```python
import github
from github import formatting
from github.formatting import shorten_url
from github.webhook import setup_webhook, shutdown_webhook
```

to

```python
from . import formatting
from .formatting import shorten_url
from .webhook import setup_webhook, shutdown_webhook
```

and from webbhook.py

```python
from github.formatting import get_formatted_response
```
to
```python
from .formatting import get_formatted_response
```


I'd make a pull request, but this is like the first time I've used Python so I'm pretty sure there is a better way to do it.

**Comment by maxpowa** [comment]
@Techbot121 I'm pretty sure that's actually how I'm supposed to do these imports haha

**Comment by Strykar** [comment]
As of today, `pip install sopel_modules.github` or `pip install --upgrade sopel_modules.github` doesn't fix it on Slackware 14.2/python-2.7

**Comment by dgw** [comment]
@Strykar Does 0.1.3 (released a couple days ago) fix this? As far as I know, it was resolved in 5502ddb (from #2) but just not released until now.

**Comment by dgw** [comment]
Assumed resolved based on commit history. Closing pending reports of this still happening.
